const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST'
const GET_POSTS_RECEIVE = 'GET_POSTS_RECEIVE'
const GET_POSTS_FAILURE = 'GET_POSTS_FAILURE'

export {
  GET_POSTS_REQUEST,
  GET_POSTS_RECEIVE,
  GET_POSTS_FAILURE
}